pipeline {
  agent any

  environment {
    GH_API_URL = 'https://github.com/gdelaunay/Sessions-API.git'
    GH_WEB_URL = 'https://github.com/gdelaunay/Sessions-Web.git'
    API_FOLDER = 'Sessions-API'
    WEB_FOLDER = 'Sessions-Web'
  }

  stages {
    
    stage('Checkout des dépôts GitHub ... ') {
        steps {
            dir(WEB_FOLDER) {
                git url: 'https://github.com/gdelaunay/Sessions-Web.git', branch: 'main'
            }
            dir(API_FOLDER) {
                git url: 'https://github.com/gdelaunay/Sessions-API.git', branch: 'main'
            }
        }
    }
         
    stage('Modifications pour HTTPS ... '){
        steps {
            sh'''
                sed -i "s|const sessionsApiUrl_HTTPS =.*|const sessionsApiUrl_HTTPS = 'https://sessions.gdelaunay.fr/api';|" ${WEB_FOLDER}/src/app/app.ts
                sed -i "s|export const sessionsApiUrl.*|export const sessionsApiUrl: string = sessionsApiUrl_HTTPS;|" ${WEB_FOLDER}/src/app/app.ts
                cp ../HTTPS/sessions/compose.yaml ${API_FOLDER}/${API_FOLDER}/compose.yaml
                cp ../HTTPS/sessions/default.conf ${API_FOLDER}/${API_FOLDER}/nginx/conf.d/default.conf 
            '''
        }
    }
   
    stage('Build de l\'image Session-Web ... ') {
      steps {
        sh '''
            docker compose -f "${WEB_FOLDER}/compose.yaml" build
        '''
      }
    }     
    
    stage('Approvisionnement des secrets ... ') {
      steps {
        sh '''
            cp ../secrets/sessions.env "./${API_FOLDER}/${API_FOLDER}/.env"
        '''
      }
    }
    
    stage('Arrêt des anciens containers ... ') {
      steps {
        sh '''
          docker compose -f "${API_FOLDER}/${API_FOLDER}/compose.yaml" down || true
        '''
      }
    }
    
    stage('Génération du certificat SSL (seulement si nécessaire) ... '){
        steps{
            sh'''
              docker stop nginx-proxy-manager
              docker run --rm -p 80:80 -v "${PWD}/${API_FOLDER}/${API_FOLDER}/nginx/certs:/etc/letsencrypt" certbot/certbot certonly --standalone --keep-until-expiring -d sessions.gdelaunay.fr --non-interactive --agree-tos -m contact@gdelaunay.fr
              docker start nginx-proxy-manager
            '''
        }
    }
    
    stage('Build et lancement ... ') {
      steps {
        sh '''
          docker compose -f "${API_FOLDER}/${API_FOLDER}/compose.yaml" up -d --build
        '''
      }
    }
  }
}
